project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"       # Render all QMDs in the root
    - "!_dev/*"     # Explicitly exclude the dev folder (double-safety)
    - "!README.md"  # Standard exclusion for info files

book:
  title: "MVR Data Science User Guide"
  author: 
    - Michael Dougherty, Geographer
    - Barrie Chileen Martinez, Geographer
  date: "3/24/2026"
  repo-url: https://github.com/MVR-GIS/MVR-User-Guide
  page-navigation: false
  search: true

  chapters:
    - index.qmd
    - part: Git Repos
      chapters:
        - repo-gpg-commit-signing.qmd
        - repo-create-generic-python-repo.qmd
    - part: "R Projects"
      chapters:
        - r-ROracle-setup.qmd
        - r-Deploy-shiny.qmd
    - part: "AI Workflows"
      chapters:
        - ai-workflows.qmd
    - part: "Data Governance"
      chapters:
        - gov-dbt-setup.qmd      
  appendices:
    - ref-references.qmd

sidebar:
  style: "docked"
  background: light
page-footer:
  left: "Made with love by USACE"
  background: light

bibliography: [ref-references.bib]

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    highlight-style: arrow

editor: source

